DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS results;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user'
);

CREATE TABLE results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  gakunen INTEGER,
  temp TEXT NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
);